### PR TITLE
Terminate TfBuilder in case there were 5 consecutive failed status updates (so far nodes drop out of the run silently)

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by cuveland** [comment]
Looks fine to me. Code is protected by mUpdateLock, so no race conditions.

**Comment by cuveland** [comment]
I have to take that back. As Gvozden points out, this code could throw an unhandled exception from a worker thread.

**Comment by davidrohr** [comment]
Well, the idea is exactly to throw an unhandled exception to kill TfBuilder, such that ODC sees that the node is in a bad state :). If you want to do that in a cleaner way, fine with me :).

**Comment by cuveland** [comment]
I get the idea. But to my understanding, that is not what will necessarily happen. ;-)

**Comment by davidrohr** [comment]
ok, but then, do you know how to do it properly? I have to admit that I do not have sufficient knowledge of the TfBuilder internals. On the other hand, I don't see the problem with this PR. If the PR doesn't work, it would anyway only apply to a broken situation where the node is already dead.

**Comment by davidrohr** [comment]
no more feedback received

**Pull request closed without merging**
