### PR TITLE
adopt namespaced fairmq api consistently

### PR DESCRIPTION
**Pull request by dennisklein**
see https://github.com/FairRootGroup/FairMQ/discussions/423

### CODE REVIEW

**Comment by dennisklein** [comment]
Should I rebase this or do you want to adapt yourself once the old names/headers are deprecated in an upcoming FairMQ release?

**Comment by ironMann** [comment]
Rebase is always appreciated 👍

**Comment by dennisklein** [comment]
Done.

**Comment by cuveland** [comment]
This is now merged as part of #175.

**Pull request closed without merging**
