### PR TITLE
Wip v0.8.0

### PR DESCRIPTION
**Pull request by ironMann**
- enable specified detector id with rdhv6
- rework logging to delay fmt interpolation

### CODE REVIEW

**Comment by ironMann** [comment]
@davidrohr this shoud be able to feed 2 different sessions

**Comment by davidrohr** [comment]
Thx @ironMann : Can you tell me what I have to change in the command line?
- I believe I don't need a second channel, I just make both dpl proxies connect to the same?
- What do I do with the session name? In the last command line you sent me, StfBuilder had `--session default` in its command line. Do I still need this? I assume the 2 dpl workflows I will start will need two different session names?

**Comment by ironMann** [comment]
@davidrohr the command should be unchanged. StfBuilder will not communicate with the rest of the chain using the main shared memory segment where the session is used. And both proxies should pull/connect to one channel of the StfBuilder

**Comment by davidrohr** [comment]
ok, in that case, can I just remove the `--session default` from both StfBuilder and the dpl workflows?
Why was that parameter there in the first place?

**Pull request merged**
