### PR TITLE
Enable all logs from FairLogger

### PR DESCRIPTION
**Pull request by rbx**
Enable all logs from FairLogger regardless of NDEBUG setting.

### CODE REVIEW

**Comment by ironMann** [comment]
@rbx This is a bit problematic. I am not affected by this since I don't use LOG() macros. So all log levers from dd processes is visible. 
This would print more logs from FMQ libs, but only the ones from include files AND if the order of includes happens to be correct. And logs from fmq and other fmq libraries (compiled ones) will still be missing.

**Comment by rbx** [comment]
Then either we change the default in alidist or compile without NDEBUG to debug properly.

**Comment by ironMann** [comment]
Release build should not be built without NDEBUG (nothing to do with the current topic of logging). First, assert() statements migh inpact on performance of the release build, and second we don't want an assertion to Abort the execution (even though this would indicate a BUG). 
IMO, the way to go here is to modify the alidist.

**Comment by ironMann** [comment]
closing, handled in alidist

**Pull request closed without merging**
