### PR TITLE
Wip v0.8.0

### PR DESCRIPTION
**Pull request by ironMann**
use RegionAllocatorResource for o2 header messages
shmem: remove FMQUnsynchronizedPoolMemoryResource class
shmem: merge received feee blocks and allow zero allocs
debug: fix split payload check 
Utils: give names to posix threads
stfb: persist memory resources until DeviceReset
file reader: avoid allocation when reading O2 Stack from file
shm region: destroy shm region before other members. frag estimation

### CODE REVIEW

**Comment by ironMann** [comment]
@davidrohr this should fix crashes with shm on exiting

**Comment by davidrohr** [comment]
@ironMann : I tried it several times and didn't have any issues any more. Thx!

Next, perhaps we could check if we could add an iteration counter, and a shutdown command to the DPL workflow.
In DPL, apparently one sends some kind of EOS (End of Stream) signal. Perhaps we can quickly discuss this in the full system test meeting today. @ktf or @shahor02 might know how to do it.

**Comment by davidrohr** [comment]
@ironMann : One more remark. Can it be that the exiting is synchronized with the rate? i.e. when I put a sender rate of 0.01 hz, it can delay the exit by up to 100 seconds?

**Comment by ironMann** [comment]
@davidrohr probably. the rate keeping threads are sleeping for too long to notice the exit signal in time... I'll try to improve

**Comment by ktf** [comment]
The end of stream is a standard O2 Message. The code which sends it is in `Framework/Core/src/DataProcessingHelpers.cxx` and the message is basically an empty `o2::framework::SourceInfoHeader`.

**Pull request merged**
