### PR TITLE
stfb: pause/resume file source

### PR DESCRIPTION
**Pull request by ironMann**

### CODE REVIEW

**Comment by ironMann** [comment]
@davidrohr You can now pause/resume by pressing [s]top and [r]un in the interactive mode.

**Comment by davidrohr** [comment]
@ironMann : Thx, will it exclude the pause time from the rate reporting, I.e. compute the rate as nTimeFramesSent / (totalTime - pauseTime)?

**Comment by davidrohr** [comment]
@ironMann : Thx, will it exclude the pause time from the rate reporting, I.e. compute the rate as nTimeFramesSent / (totalTime - pauseTime)?

**Comment by davidrohr** [comment]
ah ok, forget that stupid question, you just start counting from when we resume, that is ok as well.

**Comment by ironMann** [comment]
hm, actually the reported rate will be wrong. Let me fix that...

**Pull request merged**
