### PR TITLE
Support for reusing shm regions

### PR DESCRIPTION
**Pull request by ironMann**
To reuse existing shm regions, add the optional region ID parameter:

- StfBuilder (file source region): `--data-source-region-shmid` and `--data-source-header-shmid`

- TfBuilder: `--tf-data-region-id` and `--tf-hdr-region-id`

### CODE REVIEW

**Comment by ironMann** [comment]
@davidrohr can you test if this works?

**Comment by davidrohr** [comment]
sure, will check tonight.

**Comment by davidrohr** [comment]
@ironMann : Thx, I tested it and it works. However, I found one quite annoying behavior:
When the shm region sizes that I specify in the management tool do not exactly match the sizes that are passed to datadistribution (I had `128 << 30` v.s. `128*10^9`) the data gets somehow corrupted and the raw readers are crashing with corrupt data.
Could you add a check, that when you open an existing region, then that reagion must have the correct size?

**Comment by ironMann** [comment]
@rbx Is there a size check when adopting existing region? See the previous comment.

**Comment by rbx** [comment]
There is no size check. I'll see if i can add one.

**Comment by davidrohr** [comment]
We should actually see how we handle this. For the managed regions, the first process generates the segment with its configured size. Another process will just use it, even if a different size was set for it. But for managed regions it will just work in the sense that large messages will not fit, but no data is corrupted. So here I would not add a check.
For the unmanaged region however this is different, since if the user manages the region himself, I think he should expect to get a region of the requested size.

**Comment by rbx** [comment]
I've added a check in fmq, will be included in next patches. The check only checks UnamangedRegion.

**Pull request merged**
