### PR TITLE
Fix broken compilation on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by mfasDa**
- Add ignore_unused lambda ignoring return value
  of nice calls raising a warning for unused return value
  treated as error due to Werror
- Add compiler flag ldl if present

### CODE REVIEW

**Comment by mfasDa** [comment]
Fixing https://github.com/AliceO2Group/DataDistribution/issues/102

**Comment by mfasDa** [comment]
@ironMann Could you please have a look at this pull request!

**Comment by ironMann** [comment]
@mfasDa sorry, can you check if dev or v1.0.1 works for you? I bundled your fixes with #106

**Comment by mfasDa** [comment]
Seems to be already merged, closing

**Comment by mfasDa** [comment]
@ironMann Just saw, thanks! Let me quickly check whether it builds now on Ubuntu

**Comment by mfasDa** [comment]
@ironMann Still getting an error (due to Werror) with the nice calls

```
2021-07-29@15:21:32:DEBUG:DataDistribution:DataDistribution:aliceo2: /software/markus/alice/sw/SOURCES/DataDistribution/aliceo2/0/src/common/base/DataDistLogger.h: In lambda function:
2021-07-29@15:21:32:DEBUG:DataDistribution:DataDistribution:aliceo2: /software/markus/alice/sw/SOURCES/DataDistribution/aliceo2/0/src/common/base/DataDistLogger.h:363:18: error: ignoring return value of 'int nice(int)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
2021-07-29@15:21:32:DEBUG:DataDistribution:DataDistribution:aliceo2:   363 |       (void) nice(+1);
2021-07-29@15:21:32:DEBUG:DataDistribution:DataDistribution:aliceo2:       |              ~~~~^~~~
2021-07-29@15:21:32:DEBUG:DataDistribution:DataDistribution:aliceo2: /software/markus/alice/sw/SOURCES/DataDistribution/aliceo2/0/src/common/base/DataDistLogger.h: In lambda function:
2021-07-29@15:21:32:DEBUG:DataDistribution:DataDistribution:aliceo2: /software/markus/alice/sw/SOURCES/DataDistribution/aliceo2/0/src/common/base/DataDistLogger.h:377:18: error: ignoring return value of 'int nice(int)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
2021-07-29@15:21:32:DEBUG:DataDistribution:DataDistribution:aliceo2:   377 |       (void) nice(+10);
2021-07-29@15:21:32:DEBUG:DataDistribution:DataDistribution:aliceo2:       |              ~~~~^~~~~
```

I think the trick with the lambda function with unnamed parameters is the only workaround safely ignoring the return value on all platforms.

One more info: Compiler is this (relevant for Werror treatment):

```
gcc (Ubuntu 10.3.0-1ubuntu1~18.04~1) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mfasDa** [comment]
Superseeded by https://github.com/AliceO2Group/DataDistribution/pull/107

**Pull request closed without merging**
